AWSTemplateFormatVersion: 2010-09-09
Description: >-
  demo-sam-template

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  helloFromLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/demo-sam-template.demoSamTemplateHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
        - AWSLambdaBasicExecutionRole
